### ISSUE TITLE
where is com.serenegiant.usb.DeviceFilter ?

### ISSUE THREAD

**Issue by lkjustgo** [siarhei-luskanau/android-iot-doorbell#1]
can you give me a link?

**Comment by siarhei-luskanau** [comment]
com.serenegiant.usb.DeviceFilter is here https://github.com/siarhei-luskanau/android-iot-doorbell/tree/master/base_camera_usb/aars/libuvccamera-release

libuvccamera-release.aar comes from https://github.com/saki4510t/OpenCVwithUVC/tree/master/libuvccamera-release

**Comment by lkjustgo** [comment]
thanks☺
